config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'widgets#index'
  resources 'widgets', except: [:show] do
    get :my_widgets, on: :collection, as: :my
  end

  resource :users, only: [:show] do
    resources :widgets, only: [:index]
    collection do
      resource :sessions, only: %i[new create destroy] do
        get :links, on: :collection
      end
      resource :registrations, except: [:destroy]
      resource :passwords, except: [:destroy]
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Superclass for all other controllers
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  require 'api_service'

  before_action :init_api_service, :authenticate_user!

  def init_api_service
    token = session['token']
    auth = "#{token['token_type']} #{token['access_token']}" if token.present?
    @api_service = ApiService.new(
      'Authorization': auth
    )
  end

  private

  # it's calling after refresh token, sign up and login
  def set_session
    session['token'] = @result['data']['token']
    current_user
  end

  def current_user
    init_api_service
    @result = @api_service.me
    if @result.present? && @result['code'].zero?
      session['user'] = @result['data']['user']
    else
      flash[:error] = @result['message']
      session['user'] = session['token'] = nil
      redirect_to root_url
    end
  end

  def authenticate_user!
    refresh_token

    return unless session['token'].blank?

    flash[:error] = 'You must be logged in to view this page.'
    redirect_to root_url
  end

  def refresh_token
    token_expire_time = session['token']['created_at'] + session['token']['expires_in']

    # Refresh token expiring before 60 seconds
    return if Time.at(token_expire_time) - Time.now > 60

    # Hit refresh token API before token expire
    @result = @api_service.refresh_token(session['token']['refresh_token'])
    session['token'] = @result['data']['token']

    # update @api_service with new auth token
    init_api_service
  end

  def render_or_redirect(action)
    if @result && @result['code'].zero?
      flash[:notice] = @result['message']
      redirect_to root_url
    else
      @error = @result['message']
      render action
    end
  end
end

app/controllers/passwords_controller.rb
# frozen_string_literal: true

# It calls password related services
class PasswordsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[new create]

  def new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @result = @api_service.reset_password(password_params)
    if @result['code'].zero?
      flash[:notice] = @result['message']
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    if password_params[:password] != password_params[:confirm_password]
      @error = "New password and confirm password don't match."
      render 'edit'
    else
      @result = @api_service.change_password(password_params)
      render_or_redirect('edit')
    end
  end

  private

  def password_params
    params.permit(:email, :current_password, :password,
                  :confirm_password, :reset_password_token)
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

# It calls registration, user profile update services
class RegistrationsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[new create]

  def new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @result = @api_service.register(user_params)
    if @result['code'].zero?
      set_session
    else
      render 'new'
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @result = @api_service.update_me(user_params)
    if @result['code'].zero?
      session['user'] = @result['data']['user']
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.permit(:email, :password, :first_name, :last_name)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# Actions related to sessions, it calls authentication services
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[new create]

  def new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @result = @api_service.login(session_params)
    if @result['code'].zero?
      set_session
    else
      render 'new'
    end
  end

  def links
    @result = @api_service.me
    session['user']['first_name'] = @result['data']['user']['first_name']
    render partial: 'shared/links'
  end

  def destroy
    @result = @api_service.revoke
    session['user'] = session['token'] = nil
    redirect_to root_url
  end

  private

  def session_params
    params.permit(:username, :password)
  end
end

app/controllers/widgets_controller.rb
# frozen_string_literal: true

# Actions related to widgets, it calls widget services
class WidgetsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    result = @api_service.get_widgets(widget_params)
    return unless result.present? && result['code'].zero?

    @widgets = result['data']['widgets']
  end

  def my_widgets
    params = {term: widget_params[:my_term]}
    result = @api_service.my_widgets(params)
    if result.present? && result['code'].zero?
      @widgets = result['data']['widgets']
    end
    render action: 'index'
  end

  def new
    # Let's make hidden as default
    @kind = 'hidden'
  end

  def create
    @result = @api_service.create_widget(widget_params)
    if @result.present? && @result['code'].zero?
      flash[:notice] = 'Widget successfully created.'
      redirect_to my_widgets_url
    else
      @name = widget_params[:name]
      @description = widget_params[:description]
      render action: 'new'
    end
  end

  def edit
    @result = @api_service.show_widget(widget_params['id'])
    @name = @result['data']['widget']['name']
    @description = @result['data']['widget']['description']
    @kind = @result['data']['widget']['kind']
  end

  def update
    @result = @api_service.update_widget(widget_params)
    if @result.present? && @result['code'].zero?
      @widgets = @result['data']['widgets']
      flash[:notice] = 'Widget successfully update.'
      redirect_to my_widgets_url
    else
      @name = widget_params[:name]
      @description = widget_params[:description]
      render action: 'edit'
    end
  end

  def destroy
    @result = @api_service.destroy_widget(widget_params['id'])
    flash[:notice] = if @result['code'].zero?
                       'Widget successfully deleted.'
                     else
                       @result['message']
                     end
    redirect_to my_widgets_url
  end

  private

  def widget_params
    params.permit(:id, :term, :my_term, :user_id, :name, :description, :kind)
  end
end

app/helpers/api_helper.rb
# frozen_string_literal: true

module ApiHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/widgets_helper.rb
# frozen_string_literal: true

module WidgetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Technical Test</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'shared/header' %>
  <div class="container">
    <div class="col-lg-12">  
      <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-warning"><%= alert %></div>
      <% end %>
    </div>
    <%= yield %>
  </div>

  <div class="modal hide fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>

  <div class="modal hide fade" id="modalSignupForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>

  <div class="modal hide fade" id="modalForgotPasswordForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>

  <div class="modal hide fade" id="modalChangePasswordForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>

  <div class="modal hide fade" id="modalEditProfileForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>




</body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <%= link_to root_url, class: "navbar-brand" do %>
    <h2>Technical Test</h2>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li>
        <%= render 'widgets/search' %>
      </li>
    </ul>

    <ul class="navbar-nav navbar-light" id="header_links">
      <%=render 'shared/links' %>
    </ul>
    
  </div>
</nav>

app/views/shared/_links.html.erb
<% if session['user'] %>
  Hi <%=session['user']['first_name'] %> &nbsp; | &nbsp; 
  <li class="nav-item"><%= link_to 'My Widgets', my_widgets_path %></li> &nbsp; | &nbsp; 
  <%= link_to 'Edit Profile', edit_registrations_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modalEditProfileForm'}  %> &nbsp; | &nbsp; 
  <%= link_to 'Change Password', edit_passwords_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modalChangePasswordForm'}  %> &nbsp; | &nbsp; 
  <li class="nav-item"><%= link_to 'Logout', sessions_path, method: :delete %></li> &nbsp; 
<% else %>
  <li class="nav-item">
    <%= link_to 'Login', new_sessions_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modalLoginForm'}  %> &nbsp; | &nbsp; 
  </li>
  <li class="nav-item">
    <%= link_to 'Sign Up', new_registrations_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modalSignupForm'}  %>
  </li>
<% end %>

app/views/widgets/_form.html.erb
<div class="modal-body mx-3">
  <div class="md-form mb-5">
    <i class="fas fa-envelope prefix grey-text"></i>
    <label data-error="wrong" data-success="right" for="name">Name</label>
    <%= text_field_tag :name, @name, required: true, class: 'form-control validate' %>
  </div>
  <div class="md-form mb-5">
    <i class="fas fa-envelope prefix grey-text"></i>
    <label data-error="wrong" data-success="right" for="description">Description</label>
    <%= text_area_tag :description, @description, required: true, class: 'form-control validate' %>
  </div>
  <div class="md-form mb-5">
    <i class="fas fa-envelope prefix grey-text"></i>
    <label data-error="wrong" data-success="right">Visibility:</label>
    <div class="custom-control custom-radio">
      <%= radio_button_tag 'kind', 'hidden', @kind == 'hidden', class: 'custom-control-input', for: "kind_hidden" %>
      <label class="custom-control-label" for="kind_hidden">Hidden</label>
    </div>

    <div class="custom-control custom-radio">
      <%= radio_button_tag 'kind', 'visible', @kind == 'visible', class: 'custom-control-input', for: "kind_visible" %>
      <label class="custom-control-label" for="kind_visible">Visible</label>
    </div>
  </div>
  <div class="md-form mb-5">
    <%= button_tag 'Submit', class: 'btn btn-outline-info waves-effect ml-auto' %>
  </div>
</div>

app/views/widgets/_listing.html.erb
<% if @widgets.blank? %>
  <div class="row"> <h5>Widget not found.</h5> </div>
<% else %>
  <table class="table table-image">
    <thead>
      <tr>
        <th scope="col">Image</th>
        <th scope="col">Widget Name</th>
        <th scope="col">Description</th>
        <th scope="col">Owner</th>
        <% if session['token'].present? %>
          <th scope="col"> </th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @widgets.each do |widget| %>
        <tr>
          <td class="w-25">
            <%= image_tag widget['user']['images']['small_url'] %>
          </td>
          <td> <%= widget['name'] %></td>
          <td><%= widget['description'] %></td>
          <td><%= link_to widget['user']['name'], users_widgets_url(widget['user']['id']) %></td>
          <% if session['token'].present? %>
            <td> 
              <% if session['user']['id'] == widget['user']['id'] %>
                <%= link_to 'Edit', edit_widget_url(widget['id']) %> &nbsp; | &nbsp; 
                <%= link_to 'Delete', widgets_url(widget['id']), method: 'delete' %>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table> 
<% end %>  

app/views/widgets/_search.html.erb
<%= form_with(url: widgets_path, method: 'get', local: true, class: "form-inline my-2 my-lg-0") do %>
  <%= text_field_tag :term, params[:term], class: 'form-control mr-sm-2', placeholder: "Search all visible widgets" %>
  <%= button_tag 'Search', class: 'btn btn-outline-success my-2 my-sm-0' %>
<% end %>

app/views/widgets/edit.html.erb
<%= form_with(url: "/widgets/#{params[:id]}", method: 'patch', local: true) do %>
  <%= render 'form' %>
<% end %>

app/views/widgets/index.html.erb
  <div class="col-lg-12">
    <div class="row">
      <div class="col-lg-2">
        <h3>Widgets:</h3>
      </div>
      <% if session[:user].present? %>
      <div class="col-lg-4">
        <%= form_with(url: my_widgets_path, method: :GET, local: true, class: "form-inline my-2 my-lg-0") do %>
          <%= text_field_tag :my_term, params[:my_term], class: 'form-control mr-sm-2', placeholder: "Search my widgets" %>
          <%= button_tag 'Search', class: 'btn btn-outline-success my-2 my-sm-0' %>
        <% end %>
      </div>
      <div class="col-lg-3">
        <%= link_to 'Create Widget', new_widget_url %>
      </div>
      <% end %>
    </div>
  </div>
  <div class="row p-3">
    <div class="col-12">
      <%= render 'listing' %>
    </div>
  </div>

app/views/widgets/new.html.erb
<%= form_with(url: widgets_path, method: 'post', local: true) do %> 
  <%= render 'form' %>
<% end %>